# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reviewSwiftKnowleage' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for reviewSwiftKnowleage
 pod 'lottie-ios'
 pod 'QMUIKit'
 pod 'LLDebugToolSwift'

  target 'reviewSwiftKnowleageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'reviewSwiftKnowleageUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
